### ISSUE TITLE
On WoW Classic client the addon doesn't work at all.

### ISSUE THREAD

**Issue by maboutin81** [moody/Tamed#2]
On WoW Classic client the addon doesn't work at all.
I tried Classic Era and Classic Hardcore and in both version the Tamed Window opens... but...!
The window is empty apart from the bottom search text box and close button.
The text box is unresponsive.
The close button works.

![image](https://github.com/moody/Tamed/assets/37935743/95bb7cb2-705c-4a80-8133-349e2963624c)

**Comment by bkuepfer-revcomm** [comment]
I tried opening a PR for this issue, but I for permission errors. 

The solution that worked for me and others is the one proposed [by RicoWan](https://www.curseforge.com/wow/addons/tamed/comments),

Solution:
In the file `Tamed\src\ui\main.lua` change line 44 from
```
frame.frame:SetMinResize(650, 500)
```
to
```
frame.frame:SetResizeBounds(650, 500)
```

I hope this can be patched or made open-source!
Thanks, love this addon <3

**Comment by FireReaver** [comment]
Somehow it already broke, even with the fix I just got this error:

 

Message: ...ed/libs/AceGUI-3.0/widgets/AceGUIContainer-Frame.lua:193: attempt to call method 'SetMinResize' (a nil value)

Time: Tue Nov 28 23:29:58 2023

Count: 1

Stack: ...ed/libs/AceGUI-3.0/widgets/AceGUIContainer-Frame.lua:193: attempt to call method 'SetMinResize' (a nil value)

[string "@Interface/AddOns/Tamed/libs/AceGUI-3.0/widgets/AceGUIContainer-Frame.lua"]:193: in function `?'

[string "@Interface/AddOns/Tamed/libs/AceGUI-3.0/AceGUI-3.0.lua"]:108: in function <...nterface/AddOns/Tamed/libs/AceGUI-3.0/AceGUI-3.0.lua:97>

[string "@Interface/AddOns/Tamed/libs/AceGUI-3.0/AceGUI-3.0.lua"]:146: in function `Create'

[string "@Interface/AddOns/Tamed/src/ui/main.lua"]:40: in function `Create'

[string "@Interface/AddOns/Tamed/src/ui/main.lua"]:30: in function `Show'

[string "@Interface/AddOns/Tamed/src/ui/main.lua"]:25: in function `Toggle'

[string "@Interface/AddOns/Tamed/src/ui/minimap_icon.lua"]:21: in function `OnClick'

[string "@Interface/AddOns/Tamed/libs/LibDBIcon-1.0.lua"]:144: in function <Interface/AddOns/Tamed/libs/LibDBIcon-1.0.lua:142>

 

Locals: frame = Frame {

 0 = <userdata>

 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152

 Center = Texture {

 }

 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390

 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214

 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182

 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278

 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422

 RightEdge = Texture {

 }

 backdropInfo = <table> {

 }

 BottomEdge = Texture {

 }

 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188

 BottomLeftCorner = Texture {

 }

 BottomRightCorner = Texture {

 }

 TopEdge = Texture {

 }

 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294

 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329

 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282

 TopRightCorner = Texture {

 }

 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409

 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347

 TopLeftCorner = Texture {

 }

 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246

 SetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:399

 LeftEdge = Texture {

 }

 SetBorderBlendMode = <function> defined @Interface/SharedXML/Backdrop.lua:266

}

(*temporary) = nil

(*temporary) = Frame {

 0 = <userdata>

 OnBackdropLoaded = <function> defined @Interface/SharedXML/Backdrop.lua:152

 Center = Texture {

 }

 GetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:390

 SetupTextureCoordinates = <function> defined @Interface/SharedXML/Backdrop.lua:214

 OnBackdropSizeChanged = <function> defined @Interface/SharedXML/Backdrop.lua:182

 HasBackdropInfo = <function> defined @Interface/SharedXML/Backdrop.lua:278

 SetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:422

 RightEdge = Texture {

 }

 backdropInfo = <table> {

 }

 BottomEdge = Texture {

 }

 GetEdgeSize = <function> defined @Interface/SharedXML/Backdrop.lua:188

 BottomLeftCorner = Texture {

 }

 BottomRightCorner = Texture {

 }

 TopEdge = Texture {

 }

 ApplyBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:294

 SetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:329

 ClearBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:282

 TopRightCorner = Texture {

 }

 GetBackdropBorderColor = <function> defined @Interface/SharedXML/Backdrop.lua:409

 GetBackdrop = <function> defined @Interface/SharedXML/Backdrop.lua:347

 TopLeftCorner = Texture {

 }

 SetupPieceVisuals = <function> defined @Interface/SharedXML/Backdrop.lua:246

 SetBackdropColor = <function> defined @Interface/SharedXML/Backdrop.lua:399

 LeftEdge = Texture {

 }

 SetBorderBlendMode = <function>
